import Head from "next/head";
import Layout from "../components/layout/layout";
import { ChakraProvider, extendTheme } from "@chakra-ui/react";
import "../styles/globals.scss";
import { ReduxWrapper } from "../redux/store";

const MyApp = ({ Component, pageProps }) => (
  <ChakraProvider theme={theme} resetCSS={false}>
    <Head>
      <title>Help Pakistan</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/pakistan.svg" />
    </Head>
    <Layout>
      <Component {...pageProps} />
    </Layout>
  </ChakraProvider>
);

export default ReduxWrapper.withRedux(MyApp);

const theme = extendTheme({
  styles: {
    global: {
      body: {
        bg: "",
        color: "",
        h1: "",
        h2: "",
        h3: "",
        h4: "",
        h5: "",
        div: "",
      },
    },
  },
});
