import Head from "next/head";
import Layout from "../components/layout/layout";
import {ChakraProvider, extendTheme} from "@chakra-ui/react";
import "../styles/globals.scss";
import {ReduxWrapper} from "../redux/store";
import {theme} from "~/theme";

import socket from "~/sockets";
import {
  infoNotification,
  successNotification,
} from "~/components/fundamentals/notification/notification";
import {useSelector} from "react-redux";
import {useEffect} from "react";

const MyApp = ({Component, pageProps}) => {
  const currentUser = useSelector(({auth}) => auth.user);
  useEffect(() => {
    socket?.on("getMessage", (data) => {
      console.log(data);
      infoNotification(data.senderName, data.text);
    });
  }, []);

  useEffect(() => {
    if (currentUser != null) {
      socket?.emit("addUser", currentUser?.id);
      socket?.on("getUsers", (users) => {
        console.log(users);
      });
      socket?.emit("newNotifications", currentUser?.id);
      socket?.on("getNewNotification", (data) => {
        if (data.newMessageCount > 0) {
          infoNotification(
            "New Messages",
            `You have ${data.newMessageCount} unread messages`
          );
          socket.emit("removeNotification", currentUser?.id);
        }
      });
    }
  }, [currentUser]);

  return (
    <ChakraProvider theme={theme}>
      <Head>
        <title>Help Pakistan</title>
        <meta name="description" content="Generated by HelpPak Team" />
        <link rel="icon" href="/pakistan.svg" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </ChakraProvider>
  );
};

export default ReduxWrapper.withRedux(MyApp);
